### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by simonpoole** [stanislav-antonov/bentley-ottmann#1]
@stanislav-antonov 

Hi, I'm tentatively re-using your code in https://github.com/MarcusWolschon/osmeditor4android there is only a small issue, you don't indicate any licence for your work. Any chance you could make a statement or similar on this (Apache 2.0 would be great for us, but obviously it is your choice)?

Thanks

**Comment by stanislav-antonov** [comment]
Hi Simon, I've included Apache 2.0 license file, thank you.

**Comment by simonpoole** [comment]
Thank you Stanislav, that is very helpful.
